title: Dario Facchinetti
email: "dario.fad@gmail.com <br><a href='https://drive.google.com/file/d/1cQji7DeukMcoQFjRU8TMIkE1x-ehXNge/view?usp=sharing'>my resume</a>"
description: >-
  Dario Facchinetti's Github Pages.
  
baseurl: ""
url: "https://dariofad.github.io"
twitter_username: dario_fad
github_username:  dariofad
linkedin_username: dario-facchinetti

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown
  - pages/posts.md
  - pages/publications.md    
  - pages/teaching.md