base_url = "https://dariofad.github.io/"      # Domain name of your website
title = "Dario Facchinetti"
description = "Dario Facchinetti's GitHub Pages"
default_language = "en"
output_dir = "docs"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "one-dark"          
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Dario Facchinetti, PhD"
id = "Home" # Your id / username / handle
bio = "Assistant Professor, Software engineer"
biolinks = [
    { name = "Resume", url = "https://drive.google.com/file/d/1cQji7DeukMcoQFjRU8TMIkE1x-ehXNge/view?usp=sharing" },
    { name = "履歴書", url = "https://drive.google.com/file/d/1u08U_cjrOc1a42ib4Hf1s41PUbKu6nc1/view?usp=sharing" },    
]
avatar = "img/me.webp"            # Your avatar
links = [                             # Your links
    { name = "GitHub", icon = "github", url = "https://github.com/dariofad" },
    { name = "Twitter", icon = "twitter-x", url = "https://www.twitter.com/dario_fad" },
    { name = "Email", icon = "email", url = "mailto:dario.fad@gmail.com" },
    { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/dario-facchinetti" },
    { name = "Google Scholar", icon = "google-scholar", url = "https://scholar.google.com/citations?user=OR7QNvoAAAAJ&hl=it" },
]
# look here to get icons: https://remixicon.com/


nav_pages = [
    { name = "publications", url = "/publications" },
    { name = "teaching", url = "/teaching" },    
]

nav_separator = "-"

display_id = false                    # Display your id on homepage
projects_page = true                  # Display projects page
blur_effect = true                    # Whether to turn on blur effect on navigation bar

toc = true                            # Whether to show Table-Of-Contents by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2023 Dario Facchinetti"
footer_credits = false